# Generated by Django 5.0.4 on 2024-06-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(blank=True, max_length=50, null=True)),
                ('short_league_name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_league_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_league_date', models.CharField(blank=True, max_length=50, null=True)),
                ('league_image', models.ImageField(upload_to='league_image_media')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_image', models.ImageField(upload_to='league_image_media')),
                ('team_date', models.DateField(auto_now=True)),
                ('league_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.league')),
            ],
        ),
        
       
    ]
